### ISSUE TITLE
Have different Deploy Configuration per Configuration

### ISSUE THREAD

**Issue by FrancoTampieri** [lennyomg/VsAutoDeploy#1]
Hi,

I'm interested to have different Deploy Configuration for different Configs like Debug, Release, Remote Debug etc. etc.

Regards

Franco

**Comment by lennyomg** [comment]
Hi, Franco. It will hard to implement, unfortunately. Maybe rather later, not now. Right now I am focused in VS2017 support and integration with error list.

**Comment by lennyomg** [comment]
Anyway, I will think about it.
