### ISSUE TITLE
VS2022 compatibility ?

### ISSUE THREAD

**Issue by ghost** [lennyomg/VsAutoDeploy#10]
Could you flag it compatible with VS2022 so we can use it there ?

**Comment by lennyomg** [comment]
No. This project is deprecated. I recommend using [PsBuild](https://github.com/lennyomg/PsBuild) instead.

**Comment by ghost** [comment]
> No. This project is deprecated. I recommend using [PsBuild](https://github.com/lennyomg/PsBuild) instead.

Why ? Yours is so much better :/ It has a UI and not just scripts... Is it really broken for vs2022 ? Else i'll just recompile it on my side..
