### ISSUE TITLE
Support for other VS project types

### ISSUE THREAD

**Issue by propivot** [lennyomg/VsAutoDeploy#5]
Hi,
I wanted to use this tool to copy build artifacts from "SQL Server Integration Services" project and SSAS project, but in AutoDeploy config I can see all projects from my solution except these 2 project types. 
Is there is it possible to support these VS project types as well? 

Could it be that they are excluded, because default output directory structure is different, e.g. "/bin/development/" instead of standard "bin/Debug" ??

**Comment by lennyomg** [comment]
I believe there is something unexpected in the project tree. I can't reproduce it, but you can take a look at [DteHelpers.cs](https://github.com/lennyomg/VsAutoDeploy/blob/master/src/VsAutoDeploy/VsAutoDeploy/DteHelpers.cs) and debug `GetProjects` method.

**Comment by propivot** [comment]
I've added support for ".dwproj" (SSAS project) and ".dtproj" (SSIS) into DteHelpers.cs, in order to be able to see and config autoDeploy for these project types. Unfortunately, the VS "build" events are not triggered for these projects, so the built files are never copied into target dir. I guess that VS is using some other build process (installed via SQL Server Data Tools extension) and bypasses standard build events, which your solution depends on.  
Figuring out how to support these build types in your solution would be too time consuming for me, so I give up. 
Anyway, AutoDeploy is great helper for other proj types, so keep it going, thanks.

**Comment by propivot** [comment]
I've added support for ".dwproj" (SSAS project) and ".dtproj" (SSIS) into DteHelpers.cs, in order to be able to see and config autoDeploy for these project types. Unfortunately, the VS "build" events are not triggered for these projects, so the built files are never copied into target dir. I guess that VS is using some other build process (installed via SQL Server Data Tools extension) and bypasses standard build events, which your solution depends on.
Figuring out how to support these build types in your solution would be too time consuming for me, so I give up.
Anyway, AutoDeploy is great helper for other proj types, so keep it going, thanks.
